export const zoneNames: Record<string, string> = {
    'Limsa Lominsa': '利姆薩·羅敏薩',
    'Middle La Noscea': '中拉諾西亞',
    'Lower La Noscea': '拉諾西亚低地',
    'Eastern La Noscea': '東拉諾西亚',
    'Western La Noscea': '西拉諾西亚',
    'Upper La Noscea': '拉諾西亚高地',
    'Outer La Noscea': '拉諾西亚外地',
    'Mist': '海霧村',
    'Gridania': '格里達尼亞',
    'Central Shroud': '黑衣森林中央林區',
    'East Shroud': '黑衣森林東部林區',
    'South Shroud': '黑衣森林南部林區',
    'North Shroud': '黑衣森林北部林區',
    'The Lavender Beds': '薰衣草苗圃',
    'Ul\'dah': '烏爾達哈',
    'Western Thanalan': '西薩納蘭', 
    'Central Thanalan': '中薩納蘭',
    'Eastern Thanalan': '東薩納蘭',
    'Southern Thanalan': '南薩納蘭',
    'Northern Thanalan': '北薩納蘭',
    'The Goblet': '高腳孤丘',
    'Ishgard': '伊修加爾德',
    'Coerthas Central Highlands': '庫爾札斯中央高地',
    'Coerthas Western Highlands': '庫爾札斯西部高地',
    'Empyreum': '穹頂皓天',
    'The Sea of Clouds': '雲海',
    'Azys Lla': '魔大陸',
    'The Diadem': '雲冠諸島',
    'Idyllshire': '田園郡',
    'The Dravanian Forelands': '龍堡參天高地',
    'The Dravanian Hinterlands': '龍堡內陸低地',
    'The Churning Mists': '德拉瓦尼亞雲海',
    'Mor Dhona': '摩杜納',
    'Rhalgr\'s Reach': '神拳痕',
    'The Fringes': '基拉巴尼亞邊區',
    'The Peaks': '基拉巴尼亞山區',
    'The Lochs': '基拉巴尼亞湖區',
    'Kugane': '黃金港',
    'Shirogane': '白銀鄉',
    'The Ruby Sea': '紅玉海',
    'Yanxia': '延夏',
  'The Azim Steppe': '太陽神草原',
    'Eureka Anemos': '禁地優雷卡 常風之地',
    'Eureka Pagos': '禁地優雷卡 恆冰之地',
    'Eureka Pyros': '禁地優雷卡 湧火之地',
    'Eureka Hydatos': '禁地優雷卡 豐水之地',
    'Bozjan Southern Front': '博茲雅戰線',
    'Zadnor': '扎杜諾爾高原',
    'The Crystarium': '水晶都',
    'Eulmore': '遊末邦',
    'Lakeland': '雷克蘭德',
    'Kholusia': '珂露西亞',
    'Amh Araeng': '安穆艾蘭',
    'Il Mheg': '伊爾美格',
    'The Rak\'tika Greatwood': 'LaHee',
    'The Tempest': '黑風海',
    'Old Sharlayan': '舊薩雷安',
    'Radz-at-Han': '拉札漢',
    'Labyrinthos': '迷津',
    'Thavnair': '薩維奈',
    'Garlemald': '加雷馬',
    'Mare Lamentorum': '嘆息海',
    'Elpis': '厄爾庇斯',
    'Ultima Thule': '天外天垓',
    'Unnamed Island': '無名島',
    'Tuliyollal': '圖萊尤拉',
    'Urqopacha': '奧闊帕恰山',
    'Kozama\'uka': '克扎瑪烏卡濕地',
    'Yak T\'el': '亞克泰爾樹海',
    'Solution Nine': '九號解決方案',
    'Shaaloani': '夏洛尼荒野',
    'Heritage Found': '遺產之地',
    'Living Memory': '活生生的記憶',
    'Sinus Ardorum': '憧憬灣',
    'South Horn': '新月島南部',
    'Phaenna': '法恩娜',
    'Oizys': '俄匊斯'
}